Add experimental OpenVR support
daleglass/vircadia-builder pull request #29
Opened 2020-09-18 07:15 UTC by JulianGro

This PR makes vircadia-builder copy the missing libopenvr_api.so from the vcpkg folder into the AppImage.
While not being well tested, it does work on my system.
An AppImage build by this is available here: https://appimage.moto9000.moe/experimental/Vircadia-x86_64_v2020.2.5_openvr_experimental.AppImage

2020-09-20 17:40 UTC, daleglass requested changes

2020-09-20 17:40 UTC, daleglass commented on vircadia-builder
> +	run("cp", "-dp", "$root_dir/vcpkg/bd824a32/installed/x64-linux/lib/libopenvr_api.so", "$appimage_base/usr/lib64/libopenvr_api.so");
That won't work, vcpkg generates some random directory name (`bd824a32`) that changes over time

2020-09-20 18:09 UTC, JulianGro commented on vircadia-builder
> +	run("cp", "-dp", "$root_dir/vcpkg/bd824a32/installed/x64-linux/lib/libopenvr_api.so", "$appimage_base/usr/lib64/libopenvr_api.so");
I know. I guess now that I think about it; When that directory changes and we are on a new system, the AppImage generation will not finish.
Unfortunately this is too far out of my range of knowledge to fix. According to David the directory gets named after "(...) a new hash key".

2020-09-20 20:28 UTC, daleglass commented on vircadia-builder
> +	run("cp", "-dp", "$root_dir/vcpkg/bd824a32/installed/x64-linux/lib/libopenvr_api.so", "$appimage_base/usr/lib64/libopenvr_api.so");
I have an idea, I'll give it a try.

2020-09-20 22:38 UTC, daleglass commented
@JulianGro Last commit should hopefully fix this, could you please test it?

2020-09-21 12:03 UTC, JulianGro commented
> @JulianGro Last commit should hopefully fix this, could you please test it?

Works on my machine. Testbuild is here: https://appimage.moto9000.moe/experimental/Vircadia-x86_64_v2020.2.5_experimental_21thSept.AppImage

2020-09-21 12:03 UTC, closed without merging